template = "https://github.com/giellalt/template-lang-und"
rev_id = 275
template_sha = "ae7f0a90eca4365746c3ec57f8e39437abd6d807"

[replacements]
__GLOTTOLOG_ID__ = "stan1288"
__REPO__ = "lang-spa-x-ext-apertium"
__UND2C__ = "es"
__UNDEFINED__ = "Spanish"
__UND__ = "spa"
